import type { CueId } from './cues';
import type { AudioSource } from './settings';

/** Owner's selection from the sound catalogue, 2026-10-04. Personal overrides remain editable. */
export const DEFAULT_AUDIO_SOURCES = Object.freeze({
  'ui.click': 'synth',
  'ui.toggle': 'synth',
  'ui.error': 'file',
  'ui.open': 'synth',
  'coins.pay': 'synth',
  'coins.get': 'synth',
  'build.pop': 'synth',
  'status.joy': 'synth',
  'build.remove': 'synth',
  upgrade: 'synth',
  repair: 'synth',
  'loan.take': 'synth',
  'loan.repay': 'synth',
  study: 'synth',
  rest: 'synth',
  'shift.on': 'synth',
  'job.quit': 'synth',
  'job.return': 'synth',
  'dream.start': 'synth',
  'week.next': 'synth',
  'coin.tick': 'synth',
  'coin.minus': 'synth',
  'event.good': 'synth',
  'event.bad': 'synth',
  storm: 'synth',
  'scam.collapse': 'synth',
  'loan.emergency': 'synth',
  threat: 'synth',
  'neighbor.free': 'synth',
  freedom: 'synth',
  'freedom.level': 'synth',
  'dream.stage': 'synth',
  'dream.launch': 'synth',
  epilogue: 'synth',
  'amb.sea': 'synth',
  'amb.wind': 'synth',
  'amb.gulls': 'synth',
  'amb.rain': 'file',
  'amb.thunder': 'file',
  'music.island': 'file',
  'music.free': 'file',
  'music.epilogue': 'synth',
} satisfies Record<CueId, AudioSource>);
