// Sound acceptance (synthesis and real files). Uses external Playwright, no app dependency.
import assert from 'node:assert/strict';
import { createRequire } from 'node:module';
import { mkdir, readFile, writeFile, stat } from 'node:fs/promises';
import { resolve, join } from 'node:path';

const args = process.argv.slice(2);
const option = (name, fallback) => { const i = args.indexOf(name); return i < 0 ? fallback : args[i + 1]; };
const url = option('--url', 'http://127.0.0.1:5173');
const fixturePath = option('--fixture');
assert(fixturePath, 'Pass --fixture <fixtures.json>, generated by scripts/fixtures/sound.ts');
const fixtures = JSON.parse(await readFile(resolve(fixturePath), 'utf8'));
const output = resolve(option('--output', 'node_modules/.cache/sound-qa/results'));
await mkdir(output, { recursive: true });
const require = createRequire(import.meta.url);
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const browser = await chromium.launch({ headless: true, channel: option('--channel', process.platform === 'win32' ? 'msedge' : undefined) });
const context = await browser.newContext({ viewport: { width: 1366, height: 768 }, ignoreHTTPSErrors: true });
const page = await context.newPage();
const errors = [], autoplay = [], consoleErrors = [], checks = [], audioLogs = {};
const observe = (target) => {
  target.on('pageerror', (error) => errors.push(error.message));
  target.on('console', (message) => {
    if (/autoplay|user gesture|not allowed to start/i.test(message.text())) autoplay.push(message.text());
    if (message.type() === 'error') consoleErrors.push({ text: message.text(), url: message.location().url });
  });
};
observe(page);
await page.addInitScript(() => {
  window.__contextCreations = 0;
  window.__audioRequests = [];
  window.__qaMedia = new Set();
  const fetchOriginal = window.fetch;
  window.fetch = (...args) => {
    if (String(args[0]).includes('/audio/')) window.__audioRequests.push(String(args[0]));
    return fetchOriginal(...args);
  };
  const playOriginal = HTMLMediaElement.prototype.play;
  HTMLMediaElement.prototype.play = function (...args) { window.__qaMedia.add(this); return playOriginal.apply(this, args); };
  const Original = window.AudioContext;
  if (Original) window.AudioContext = class extends Original {
    constructor(...args) { super(...args); window.__contextCreations++; }
  };
});
const snapshot = () => page.evaluate(async () => (await import('/src/audio/engine.ts')).audio.snapshot());
async function waitSnapshot(predicate, timeout = 10000) {
  const deadline = Date.now() + timeout;
  while (Date.now() < deadline) {
    const state = await snapshot();
    if (predicate(state)) return state;
    await page.waitForTimeout(50);
  }
  assert.fail(`Audio state timed out: ${JSON.stringify(await snapshot())}`);
}
const logs = () => page.evaluate(() => window.__audioLog ?? []);
const clearLog = () => page.evaluate(() => { window.__audioLog = []; });
async function load(name, { debug = true, long = false } = {}) {
  await page.goto(url);
  await page.evaluate(({ fixture, debug, long }) => {
    localStorage.clear();
    if (debug) localStorage.setItem('archipelago.audio.debug', '1');
    const world = structuredClone(fixture.world);
    if (long) world.players[0].islandName = 'Остров Солнечной Свободы';
    localStorage.setItem('archipelago.save.v1', JSON.stringify({ world, news: [] }));
  }, { fixture: fixtures[name], debug, long });
  await page.reload();
  await page.locator('.hud').waitFor();
  await page.evaluate(() => document.fonts.ready);
  assert.equal(await page.evaluate(() => window.__contextCreations), 0, `${name}: context created before gesture`);
  assert.equal((await snapshot()).contextState, 'locked');
  assert.equal(await page.evaluate(() => window.__audioRequests.length + window.__qaMedia.size), 0, 'Audio requested before gesture');
}
async function unlock() {
  await page.locator('.badge .title').click();
  await waitSnapshot((state) => state.contextState === 'running');
}
function inOrder(entries, cues) {
  let index = -1;
  for (const cue of cues) {
    index = entries.findIndex((entry, i) => i > index && entry.cue === cue);
    assert(index >= 0, `Missing or out-of-order cue ${cue}: ${entries.map((entry) => entry.cue).join(', ')}`);
  }
}
async function record(name) { audioLogs[name] = await logs(); checks.push(name); }
const cueRow = (cue) => page.locator('.sound-cue').filter({ has: page.locator('code', { hasText: new RegExp(`^${cue.replace(/[.]/g, '\\.')}$`) }) });
async function choose(cue, source) { await cueRow(cue).locator('select').selectOption(source); }
async function jpeg(name) {
  const path = join(output, `${name}.jpg`);
  await page.screenshot({ path, type: 'jpeg', quality: 62 });
  assert((await stat(path)).size < 150 * 1024, `${name} exceeds screenshot budget`);
}

try {
  await page.goto(url);
  await page.evaluate(() => { localStorage.clear(); localStorage.setItem('archipelago.audio.debug', '1'); });
  await page.reload();
  await page.getByRole('button', { name: 'Начать игру', exact: true }).waitFor();
  assert.equal(await page.evaluate(() => window.__contextCreations), 0);
  assert.equal(await page.evaluate(() => '__audioLog' in window), false);
  await page.getByRole('button', { name: 'Начать игру', exact: true }).click();
  await page.locator('.hud').waitFor();
  await page.waitForFunction(() => ['music.island', 'amb.sea', 'amb.wind'].every((cue) => (window.__audioLog ?? []).some((entry) => entry.cue === cue)));
  const initial = await logs();
  assert(initial.some((entry) => entry.cue === 'ui.click' && entry.source === 'synth'));
  await waitSnapshot((state) => ['music.island', 'amb.sea', 'amb.wind'].every((cue) => state.voices.some((voice) => voice.cue === cue && voice.source === (cue === 'music.island' ? 'file' : 'synth') && voice.choice === voice.source)));
  for (const cue of ['music.island', 'amb.sea', 'amb.wind']) assert(initial.some((entry) => entry.cue === cue), `Missing starting layer ${cue}`);
  const defaults = await page.evaluate(async () => {
    const { CUE_IDS, CUES } = await import('/src/audio/cues.ts'); const { getCueSource } = await import('/src/audio/settings.ts');
    return CUE_IDS.map((cue) => ({ cue, bus: CUES[cue].bus, source: getCueSource(cue) }));
  });
  const ownerRecordings = new Set(['ui.error', 'amb.rain', 'amb.thunder', 'music.island', 'music.free']);
  for (const item of defaults) assert.equal(item.source, ownerRecordings.has(item.cue) ? 'file' : 'synth', `${item.cue}: unexpected default`);
  assert(!(await page.evaluate(() => window.__audioRequests)).some((path) => path.includes('/sfx/') && !path.endsWith('/ui-error.mp3')), 'Synth defaults still preload recorded effects');
  assert(!(await page.evaluate(() => window.__audioRequests)).some((path) => /amb-(sea|wind|gulls)/.test(path)), 'Synth nature defaults loaded their recordings');
  checks.push('owner-selected-default-five-recordings-and-37-synthesized-sounds');
  await record('newGame');

  const actionCues = {
    buyAsset: ['coins.pay', 'build.pop'], buyStatus: ['coins.pay', 'build.pop', 'status.joy'], buyScam: ['coins.pay', 'build.pop'],
    buyNoCash: ['ui.error'], sellAsset: ['coins.get', 'build.remove'], upgradeAsset: ['coins.pay', 'upgrade'],
    repairAsset: ['coins.pay', 'repair'], takeLoan: ['coins.get', 'loan.take'], repayLoan: ['loan.repay'],
    study: ['coins.pay', 'study'], rest: ['coins.pay', 'rest'], setExtraShift: ['shift.on'],
    quitJob: ['job.quit'], returnToWork: ['job.return'], buildDream: ['coins.pay', 'dream.start'],
  };
  for (const [name, expected] of Object.entries(actionCues)) {
    await load(name); await unlock(); await clearLog();
    const success = await page.evaluate(async (action) => (await import('/src/store.ts')).useGame.getState().act(action), fixtures[name].action);
    assert.equal(success, name !== 'buyNoCash', `${name}: unexpected action result`);
    await page.waitForFunction((cue) => (window.__audioLog ?? []).some((entry) => entry.cue === cue), expected.at(-1));
    inOrder(await logs(), expected);
    if (name === 'buyScam') assert(!(await logs()).some((entry) => entry.cue === 'status.joy' || entry.cue === 'scam.collapse'));
    await record(name);
  }

  const weekCues = { coinWeek: [], storm: ['storm'], freedom: ['freedom'], freedomLevel: ['freedom.level'],
    dreamStage: ['dream.stage'], dreamDone: ['dream.launch', 'epilogue'], neighborFree: ['neighbor.free'], scamCollapse: ['scam.collapse'] };
  const eventCues = new Set(['dream.launch', 'epilogue', 'freedom', 'freedom.level', 'dream.stage', 'storm', 'scam.collapse', 'loan.emergency', 'threat', 'job.return', 'event.bad', 'event.good', 'neighbor.free']);
  for (const [name, expected] of Object.entries(weekCues)) {
    if (!fixtures[name]) continue;
    await load(name); await unlock(); await clearLog();
    await page.evaluate(async () => {
      const { useGame } = await import('/src/store.ts');
      window.__qaGame = useGame;
      window.__floatLog = [];
      const seen = new Set();
      window.__floatUnsubscribe = useGame.subscribe((state) => {
        for (const label of state.floats) if (!seen.has(label.id)) {
          seen.add(label.id); window.__floatLog.push({ t: performance.now(), ...label });
        }
      });
    });
    await page.getByRole('button', { name: /Следующая неделя/ }).click();
    await page.waitForFunction(() => !window.__qaGame.getState().busy);
    const positiveCount = await page.evaluate(async () => {
      const { useGame } = await import('/src/store.ts'); const report = useGame.getState().world.lastReport.players.p1;
      return 1 + report.assetIncome.filter((item) => item.amount > 0).length;
    });
    // Wait for the last scheduled float, including status and schooner upkeep labels.
    const floatCount = await page.evaluate(async () => {
      const { useGame } = await import('/src/store.ts'); const { world } = useGame.getState(); const report = world.lastReport.players.p1;
      return 1 + report.assetIncome.filter((item) => item.amount > 0).length + report.upkeep.filter((item) => item.amount > 0
        && (item.assetUid === 'dream' || world.players[0].owned.some((asset) => asset.uid === item.assetUid && ['garden', 'fountain', 'statue', 'yacht'].includes(asset.defId)))).length;
    });
    await page.waitForFunction((count) => window.__floatLog.length >= count, floatCount);
    const entries = await logs();
    inOrder(entries, ['week.next', ...expected]);
    const coins = entries.filter((entry) => entry.cue === 'coin.tick');
    assert.equal(coins.length, Math.min(12, positiveCount), `${name}: positive coin count`);
    assert.deepEqual(coins.map((entry) => entry.pitchStep), coins.map((_, i) => Math.min(i, 7)));
    assert(entries.filter((entry) => eventCues.has(entry.cue)).length <= 2, `${name}: more than two week events`);
    const floats = await page.evaluate(() => { window.__floatUnsubscribe(); return window.__floatLog; });
    const negatives = floats.filter((label) => label.tone === 'neg');
    const minus = entries.filter((entry) => entry.cue === 'coin.minus');
    assert.equal(minus.length, negatives.length, `${name}: negative coin count`);
    const positiveFloats = floats.filter((label) => label.tone === 'pos').slice(0, 12);
    for (let i = 0; i < coins.length; i++) assert(Math.abs(coins[i].t - positiveFloats[i].t) < 40, `${name}: coin and float not synchronized`);
    for (let i = 0; i < minus.length; i++) assert(Math.abs(minus[i].t - negatives[i].t) < 40);
    if (name === 'storm') {
      assert.equal((await snapshot()).weather, 'storm');
      assert((await snapshot()).voices.some((voice) => voice.cue === 'amb.rain'));
      await waitSnapshot((state) => state.weather === 'clear');
      await page.waitForTimeout(1600);
      assert(!(await snapshot()).voices.some((voice) => voice.cue === 'amb.rain'));
    }
    if (name === 'freedom') assert.equal((await snapshot()).scene, 'free');
    if (name === 'dreamDone') {
      assert.equal((await snapshot()).scene, 'epilogue');
      const launch = entries.find((entry) => entry.cue === 'dream.launch');
      const ending = entries.find((entry) => entry.cue === 'epilogue');
      assert(ending.t - launch.t > 800, 'Launch must precede the modal');
      await waitSnapshot((state) => state.scene === 'free', 11000);
    }
    await record(name);
  }

  await load('buyAsset');
  await page.goto(`${url}/?sound`); await page.getByRole('heading', { name: 'Звуки острова' }).waitFor();
  await choose('amb.sea', 'file');
  await page.locator('.sound-scene').filter({ hasText: /▶ Остров/ }).click();
  await page.locator('.sound-nature button').click();
  await page.getByRole('switch', { name: /Шторм/ }).check();
  await waitSnapshot((state) => state.scene === 'island' && state.weather === 'storm'
    && ['music.island', 'amb.sea'].every((cue) => state.voices.some((voice) => voice.cue === cue && voice.source === 'file')));
  for (const source of ['synth', 'file']) {
    await choose('music.island', source); await choose('amb.sea', source);
    await waitSnapshot((state) => state.scene === 'island' && state.weather === 'storm' && state.ambience
      && ['music.island', 'amb.sea'].every((cue) => state.voices.some((voice) => voice.cue === cue && voice.source === source && voice.choice === source)));
    await page.waitForTimeout(2700);
    const switched = await snapshot();
    for (const cue of ['music.island', 'amb.sea']) assert.equal(switched.voices.filter((voice) => voice.cue === cue).length, 1, `${cue}: outgoing layer leaked`);
  }
  checks.push('live-source-switches-preserve-music-scene-and-storm');
  await choose('epilogue', 'synth');
  assert.equal(await cueRow('music.epilogue').locator('select').inputValue(), 'synth');
  await choose('music.epilogue', 'file');
  assert.equal(await cueRow('epilogue').locator('select').inputValue(), 'file');
  await choose('coins.pay', 'file'); await choose('music.island', 'synth'); await choose('amb.sea', 'synth');
  const choiceBeforeComparison = await page.evaluate(async () => (await import('/src/audio/settings.ts')).getAudioSettings().sources);
  await page.getByRole('button', { name: '■ Остановить всё', exact: true }).click(); await clearLog();
  const paymentLabel = await cueRow('coins.pay').locator('b').innerText();
  await page.getByRole('button', { name: `Послушать синтез: ${paymentLabel}`, exact: true }).click();
  await page.waitForFunction(() => (window.__audioLog ?? []).some((entry) => entry.cue === 'coins.pay' && entry.source === 'synth'));
  assert.deepEqual(await page.evaluate(async () => (await import('/src/audio/settings.ts')).getAudioSettings().sources), choiceBeforeComparison, 'Comparison changed the saved game profile');
  await page.reload(); await page.getByRole('heading', { name: 'Звуки острова' }).waitFor();
  for (const [cue, source] of [['coins.pay', 'file'], ['build.pop', 'synth'], ['music.island', 'synth'], ['amb.sea', 'synth']]) {
    assert.equal(await cueRow(cue).locator('select').inputValue(), source, `${cue}: source did not survive reload`);
  }
  assert.equal(await page.evaluate(() => window.__contextCreations), 0);
  await page.goto(url); await page.locator('.hud').waitFor(); await unlock();
  await page.waitForFunction(async () => (await import('/src/audio/engine.ts')).audio.decoded.has('/audio/sfx/coins-pay.mp3'));
  await clearLog();
  assert.equal(await page.evaluate(async (action) => (await import('/src/store.ts')).useGame.getState().act(action), fixtures.buyAsset.action), true);
  await page.waitForFunction(() => (window.__audioLog ?? []).some((entry) => entry.cue === 'build.pop'));
  const mixedGame = await logs();
  assert(mixedGame.some((entry) => entry.cue === 'coins.pay' && entry.source === 'file'));
  assert(mixedGame.some((entry) => entry.cue === 'build.pop' && entry.source === 'synth'));
  assert((await snapshot()).voices.some((voice) => voice.cue === 'music.island' && voice.source === 'synth'));
  assert((await snapshot()).voices.some((voice) => voice.cue === 'amb.sea' && voice.source === 'synth'));
  assert(!(await page.evaluate(() => window.__audioRequests)).some((path) => /build-pop|amb-sea|\/music\//.test(path)), 'Synth choices loaded their recorded files');
  await record('mixed-source-profile-persists-and-controls-game');

  await load('developed'); await unlock();
  await page.locator('.audio-button').click();
  await page.getByRole('dialog', { name: 'Звук', exact: true }).waitFor();
  await page.getByRole('switch', { name: 'Звук включён', exact: true }).uncheck();
  assert.equal((await snapshot()).master, 0);
  const previous = (await logs()).length;
  await page.evaluate(async () => (await import('/src/audio/engine.ts')).audio.play('week.next'));
  assert.equal((await logs()).length, previous, 'Muted effects should not be played');
  for (const label of ['Музыка', 'Эффекты', 'Природа']) {
    const slider = page.getByRole('slider', { name: label, exact: true });
    const id = await slider.getAttribute('id');
    const committed = (value) => page.waitForFunction(({ id, value }) => document.getElementById(id)?.getAttribute('aria-valuetext') === `${value}%`, { id, value });
    await slider.press('Home'); await committed(0);
    for (let step = 1; step <= 23; step++) { await slider.press('ArrowRight'); await committed(step); }
  }
  const mutedSettings = await page.evaluate(async () => (await import('/src/audio/settings.ts')).getAudioSettings());
  for (const bus of ['music', 'sfx', 'ambience']) assert.equal(mutedSettings[bus], 0.23);
  await page.reload(); await page.locator('.hud').waitFor();
  await page.locator('.audio-button').click();
  assert.equal(await page.getByRole('switch', { name: 'Звук включён', exact: true }).isChecked(), false);
  for (const label of ['Музыка', 'Эффекты', 'Природа']) assert.equal(await page.getByRole('slider', { name: label, exact: true }).inputValue(), '0.23');
  await page.getByRole('switch', { name: 'Звук включён', exact: true }).check();
  // Idle AudioParam.value can retain the last computed quantum; assert gain while SFX really renders.
  await page.evaluate(async () => (await import('/src/audio/engine.ts')).audio.play('week.next'));
  await waitSnapshot((state) => Object.values(state.buses).every((volume) => Math.abs(volume - 0.23) < 0.000001));
  await page.keyboard.press('Escape');
  assert.equal(await page.locator('.audio-panel').count(), 0);
  assert.equal(await page.locator('.audio-button').evaluate((element) => element === document.activeElement), true);
  checks.push('settings-persistence-mute-and-buses');

  await page.evaluate(() => { Object.defineProperty(document, 'hidden', { configurable: true, value: true }); document.dispatchEvent(new Event('visibilitychange')); });
  await waitSnapshot((state) => state.contextState === 'suspended');
  const mediaPositions = await page.evaluate(() => [...window.__qaMedia].filter((media) => media.src && !media.ended).map((media) => ({ time: media.currentTime, paused: media.paused })));
  assert(mediaPositions.every((media) => media.paused), 'Hidden music stream still playing');
  await page.waitForTimeout(250);
  const hiddenPositions = await page.evaluate(() => [...window.__qaMedia].filter((media) => media.src && !media.ended).map((media) => media.currentTime));
  mediaPositions.forEach((media, i) => assert(Math.abs(media.time - hiddenPositions[i]) < .05, 'Hidden stream advances'));
  await page.evaluate(() => { delete document.hidden; document.dispatchEvent(new Event('visibilitychange')); });
  await waitSnapshot((state) => state.contextState === 'running');
  await page.evaluate(() => {
    Object.defineProperty(document, 'hidden', { configurable: true, value: true }); document.dispatchEvent(new Event('visibilitychange'));
    delete document.hidden; document.dispatchEvent(new Event('visibilitychange'));
  });
  await page.waitForTimeout(100);
  assert.equal((await snapshot()).contextState, 'running');
  checks.push('visibility-suspend-resume-and-race');

  await page.evaluate(async () => {
    const { audio } = await import('/src/audio/engine.ts');
    audio.setAmbience(false); audio.setAmbience(true);
    audio.setWeather('storm'); audio.setWeather('clear'); audio.setWeather('storm');
  });
  await page.waitForTimeout(1700);
  for (const cue of ['amb.sea', 'amb.wind', 'amb.rain']) assert((await snapshot()).voices.some((voice) => voice.cue === cue));
  const capacity = await page.evaluate(async () => {
    const { audio } = await import('/src/audio/engine.ts'); const { CUE_IDS } = await import('/src/audio/cues.ts');
    let max = 0;
    for (let round = 0; round < 3; round++) for (const cue of CUE_IDS) { audio.play(cue); max = Math.max(max, audio.snapshot().voices.length); }
    audio.play('coin.tick', { delayMs: 3000 });
    const { useGame } = await import('/src/store.ts'); useGame.getState().resetGame();
    return { max, stopped: audio.snapshot() };
  });
  assert(capacity.max <= 16); assert.equal(capacity.stopped.voices.length, 0); assert.equal(capacity.stopped.pending, 0);
  checks.push('voice-limit-fast-nature-toggle-and-reset');

  await load('initial', { debug: false }); await unlock();
  assert.equal(await page.evaluate(() => '__audioLog' in window), false);
  checks.push('no-debug-global-without-flag');

  await page.goto(`${url}/?sound`);
  await page.getByRole('heading', { name: 'Звуки острова' }).waitFor();
  await page.evaluate(() => localStorage.setItem('archipelago.audio.debug', '1'));
  const catalogInfo = await page.evaluate(async () => {
    const { CUE_IDS, CUES } = await import('/src/audio/cues.ts'); const { getCueSource } = await import('/src/audio/settings.ts');
    return CUE_IDS.map((cue) => ({ cue, label: CUES[cue].label, source: getCueSource(cue), files: !!CUES[cue].files?.length }));
  });
  const catalog = catalogInfo.map((item) => item.cue);
  assert.equal(await page.locator('.sound-cue').count(), catalog.length);
  for (const cue of catalog) {
    await page.getByRole('button', { name: '■ Остановить всё', exact: true }).click(); await clearLog();
    await cueRow(cue).locator('.sound-play').click();
    await page.waitForFunction((cue) => (window.__audioLog ?? []).some((entry) => entry.cue === cue), cue);
    audioLogs[`catalog:${cue}`] = await logs();
    assert.equal(audioLogs[`catalog:${cue}`].find((entry) => entry.cue === cue).source, catalogInfo.find((item) => item.cue === cue).source, `${cue}: catalogue ignored the saved choice`);
  }
  await page.getByRole('button', { name: '■ Остановить всё', exact: true }).click(); await clearLog();
  await page.getByRole('button', { name: /Каскад монет ×8/ }).click();
  await page.waitForFunction(() => (window.__audioLog ?? []).filter((entry) => entry.cue === 'coin.tick').length === 8);
  assert.deepEqual((await logs()).map((entry) => entry.pitchStep), [0, 1, 2, 3, 4, 5, 6, 7]);
  await record('showcase-all-42-cues-and-cascade');

  const fileMode = await page.evaluate(async () => { const { CUE_IDS, CUES } = await import('/src/audio/cues.ts'); return CUE_IDS.every((cue) => CUES[cue].files?.length); });
  if (fileMode) {
    for (const { cue, label } of catalogInfo) {
      await page.getByRole('button', { name: '■ Остановить всё', exact: true }).click(); await clearLog();
      await page.getByRole('button', { name: `Послушать запись: ${label}`, exact: true }).click();
      await page.waitForFunction((cue) => (window.__audioLog ?? []).some((entry) => entry.cue === cue), cue);
      const entries = await logs(); assert.equal(entries.find((entry) => entry.cue === cue).source, 'file', `${cue}: explicit recording comparison must decode or stream the real file`);
      audioLogs[`recording:${cue}`] = entries;
      assert.equal(await cueRow(cue).locator('select').inputValue(), catalogInfo.find((item) => item.cue === cue).source, `${cue}: comparison changed the game choice`);
    }
    const fetched = await page.evaluate(() => window.__audioRequests);
    assert(!fetched.some((path) => path.includes('/music/')), 'Music decoded through fetch instead of streamed');
    const decodedLoops = await page.evaluate(async () => {
      const { audio } = await import('/src/audio/engine.ts');
      return ['sea', 'wind', 'rain'].map((name) => ({ file: name, duration: audio.decoded.get(`/audio/ambience/amb-${name}.mp3`)?.duration }));
    });
    decodedLoops.forEach((loop) => assert(Math.abs(loop.duration - 30) < .001, `Browser decoder added loop padding: ${JSON.stringify(loop)}`));
    assert.equal(await page.locator('.sound-cue select').count(), 42);
    await page.getByRole('button', { name: '■ Остановить всё', exact: true }).click(); await clearLog();
    await page.getByRole('button', { name: `Послушать: ${catalogInfo.find((item) => item.cue === 'music.island').label}, вариант 2`, exact: true }).click();
    await page.waitForFunction(() => (window.__audioLog ?? []).some((entry) => entry.cue === 'music.island' && entry.source === 'file' && entry.variant === 1));
    assert(await page.evaluate(() => [...window.__qaMedia].some((media) => media.src.endsWith('/island-sicilian.mp3') && !media.paused)));
    await record('real-files-all-cues-streamed-music-and-second-variant');
    const corrupt = await context.newPage(); observe(corrupt);
    await corrupt.route('**/audio/**/*.mp3', (route) => route.fulfill({ status: 200, contentType: 'audio/mpeg', body: 'deliberately corrupt audio fixture' }));
    await corrupt.goto(`${url}/?sound`);
    await corrupt.getByRole('button', { name: `Послушать запись: ${catalogInfo.find((item) => item.cue === 'ui.toggle').label}`, exact: true }).click();
    await corrupt.waitForFunction(() => (window.__audioLog ?? []).some((entry) => entry.cue === 'ui.toggle' && entry.source === 'synth'));
    await corrupt.getByRole('button', { name: `Послушать запись: ${catalogInfo.find((item) => item.cue === 'music.island').label}`, exact: true }).click();
    await corrupt.waitForFunction(() => (window.__audioLog ?? []).some((entry) => entry.cue === 'music.island' && entry.source === 'synth'));
    audioLogs['corrupt-file-fallback'] = await corrupt.evaluate(() => window.__audioLog);
    await corrupt.close(); checks.push('real-corrupt-effect-and-stream-synth-fallback');
  }

  for (const [width, height] of [[1366, 768], [390, 844]]) {
    await page.setViewportSize({ width, height });
    await load('developed'); await page.waitForTimeout(250);
    assert.equal(await page.locator('.nb-chip:visible').count(), 4);
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false);
    await jpeg(`header-${width}`);
    await page.locator('.audio-button').click();
    const box = await page.locator('.audio-panel').boundingBox();
    assert(box.x >= 0 && box.y >= 0 && box.x + box.width <= width && box.y + box.height <= height);
    await jpeg(`panel-${width}`);
    await page.keyboard.press('Escape');
    await load('developed', { long: true });
    await page.waitForTimeout(200);
    const geometry = await page.evaluate(() => {
      const boxes = [...document.querySelectorAll('.badge .nb-chip, .audio-button, .badge > .icon-btn')]
        .filter((element) => element.getClientRects().length).map((element) => element.getBoundingClientRect());
      return boxes.map((rect) => ({ left: rect.left, right: rect.right }));
    });
    const sorted = geometry.sort((a, b) => a.left - b.left);
    for (let i = 1; i < sorted.length; i++) assert(sorted[i].left >= sorted[i - 1].right - 1, 'Header controls overlap');
    await page.goto(`${url}/?sound`); await page.getByRole('heading', { name: 'Звуки острова' }).waitFor();
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false, 'Source controls overflow showcase viewport');
    await page.locator('.sound-catalog-heading').evaluate((element) => element.scrollIntoView({ block: 'start' }));
    await jpeg(`showcase-${width}`);
  }
  checks.push('responsive-header-panel-showcase-short-long');

  for (const mode of ['unsupported', 'storage-denied']) {
    const fallback = await context.newPage(); observe(fallback);
    await fallback.addInitScript((mode) => {
      if (mode === 'unsupported') { window.AudioContext = undefined; window.webkitAudioContext = undefined; }
      else for (const method of ['getItem', 'setItem', 'removeItem']) Storage.prototype[method] = () => { throw new DOMException('Denied', 'SecurityError'); };
    }, mode);
    await fallback.goto(url);
    if (mode === 'unsupported') await fallback.evaluate(() => localStorage.clear());
    await fallback.reload();
    await fallback.getByRole('button', { name: 'Начать игру', exact: true }).click();
    await fallback.locator('.hud').waitFor();
    await fallback.getByRole('button', { name: /Следующая неделя/ }).click();
    assert.equal(await fallback.evaluate(async () => (await import('/src/store.ts')).useGame.getState().world.week), 2);
    await fallback.goto(`${url}/?sound`);
    await fallback.getByRole('heading', { name: 'Звуки острова' }).waitFor();
    await fallback.getByRole('combobox', { name: `В игре: ${catalogInfo.find((item) => item.cue === 'ui.click').label}`, exact: true }).selectOption('file');
    assert.equal(await fallback.evaluate(async () => (await import('/src/audio/settings.ts')).getCueSource('ui.click')), 'file', `${mode}: source choice should remain usable`);
    if (mode === 'storage-denied') {
      await fallback.reload(); await fallback.getByRole('heading', { name: 'Звуки острова' }).waitFor();
      assert.equal(await fallback.evaluate(async () => (await import('/src/audio/settings.ts')).getCueSource('ui.click')), 'synth', 'Denied storage should recover the default profile after reload');
    }
    await fallback.close(); checks.push(mode);
  }

  assert.equal(errors.length, 0, `Runtime errors: ${errors.join('; ')}`);
  assert.equal(autoplay.length, 0, `Autoplay warnings: ${autoplay.join('; ')}`);
  const relevantErrors = consoleErrors.filter((item) => !(item.text.includes('ERR_CERT') && /fonts\.(googleapis|gstatic)\.com/.test(item.url)));
  assert.equal(relevantErrors.length, 0, `Console errors: ${JSON.stringify(relevantErrors)}`);
  await writeFile(join(output, 'audio-log.json'), JSON.stringify(audioLogs, null, 2));
  await writeFile(join(output, 'results.json'), JSON.stringify({ checks, capacity: capacity.max, runtimeErrors: errors, autoplayWarnings: autoplay, consoleErrors, screenshots: 6 }, null, 2));
  console.log(JSON.stringify({ output, checks: checks.length, catalog: catalog.length, maximumVoices: capacity.max, errors: 0, screenshots: 6 }));
} catch (error) {
  await writeFile(join(output, 'failure.json'), JSON.stringify({ error: String(error), snapshot: await snapshot(), log: await logs(), floats: await page.evaluate(() => window.__floatLog ?? []), errors, consoleErrors }, null, 2));
  throw error;
} finally { await browser.close(); }
